"""empty message

Revision ID: 09466aacf44c
Revises: d1026de409cd
Create Date: 2024-05-22 19:16:33.539516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09466aacf44c'
down_revision = 'd1026de409cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
